#!/bin/bash


HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

# OS Information
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU Information
CPU=$(lscpu | grep "Model name" | awk -F: '{print $2}' | xargs)

# RAM Information
RAM=$(free -h | grep "Mem:" | awk '{print $2}')

# Disk Information
DISKS=$(lsblk -o NAME,SIZE,MODEL | grep -v "loop" | awk '{print $3 " (" $2 ")"}' | xargs)

# Video Card Information
VIDEO=$(lspci | grep -i vga | awk -F: '{print $2}' | xargs)

# Network Information
IP_ADDRESS=$(ip a | grep -w inet | grep -v 127.0.0.1 | awk '{print $2}' | cut -d/ -f1)
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}' | xargs)

# System Status
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | xargs)
DISK_SPACE=$(df -h | grep '^/' | awk '{print $1 " " $4}' | xargs)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -v '::' | cut -d':' -f2 | xargs)
UFW_STATUS=$(ufw status | grep Status | awk '{print $2}')

# Output the report
cat << EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
